services:
  photobook:
    container_name: photobook
    image: photobook
    build:
      context: .
      dockerfile: Photobook/Dockerfile
    dns:
      - 8.8.8.8
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: photobook.db
    hostname: photobook.db
    volumes:
      - sqlserverdata:/var/lib/sqlserver

volumes:
  sqlserverdata:
    driver: local