/*
 * Photobook
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * OpenAPI generator version: 5.3.1-SNAPSHOT
 */


import http from "k6/http";
import { group, check, sleep } from "k6";

const BASE_URL = "/";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function() {
    group("/photos", () => {
        let url = BASE_URL + `/photos`;
        // Request No. 1
        let request = http.get(url);
        check(request, {
            "Success": (r) => r.status === 200
        });
        sleep(SLEEP_DURATION);

        // Request No. 2
        // TODO: edit the parameters of the request body.
        body = {"file": http.file(open("/path/to/file.bin", "b"), "test.bin")};
        params = {headers: {"Content-Type": "multipart/form-data"}};
        request = http.post(url, body, params);
        check(request, {
            "Success": (r) => r.status === 204
        });
        sleep(SLEEP_DURATION);
    });
    group("/photos/{id}", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let url = BASE_URL + `/photos/${id}`;
        // Request No. 1
        let request = http.get(url);
        check(request, {
            "Success": (r) => r.status === 200
        });
        sleep(SLEEP_DURATION);

        // Request No. 2
        request = http.del(url);
        check(request, {
            "Success": (r) => r.status === 204
        });
        sleep(SLEEP_DURATION);
    });
}
